name: ocviewer Build

on:
  push:
    branches: [ oc_dev ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Windows Binary
        run: |
          cd flutter
          flutter pub get
          flutter build windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ocviewer-windows
          path: flutter/build/windows/runner/Release/ocviewer.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install Linux Dependencies
        run: |
          sudo apt update && sudo apt install -y build-essential libgtk-3-dev libayatana-appindicator3-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Linux AppImage
        run: |
          cd flutter
          flutter pub get
          flutter build linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ocviewer-linux
          path: flutter/build/linux/x64/release/bundle/